### ISSUE TITLE
Information update

### ISSUE THREAD

**Issue by amitguptagwl** [mwittig/restler-base#3]
As restler is no active anymore and this repository is forked with the aim for fixing any new issue for restler, I believe we should change the detail on README as well. Like linking to the package available in npm, npm installation command etc.

I've raised the pull request for that. I'll appreciate if other part can also be updated and then please publish it to npm.

**Comment by mwittig** [comment]
Fully agree. Thank you very much for your contribution. I'll take care of the remaining bits and bobs asap

**Comment by mwittig** [comment]
published restler-base@3.4.5
